// array of movies

export const movies = [
    {
      id: "nosferatu",
      title: "Nosferatu",
      image:
        "https://assets.voxcinemas.com/posters/P_HO00011813_1734505897702.jpg",
      description: "Succumb to the Darkness",
      longDescription:
        "Nosferatu is a chilling and atmospheric silent horror film that tells the story of Count Orlok, a vampire who preys upon the living. With its haunting cinematography and groundbreaking visual effects, this timeless classic remains one of the most influential horror films of all time.",
      highlight: "Now Showing",
      size: "large",
      rating: 8.5,
      duration: "01 hours 45 minutes",
      language: "English",
      releaseDate: "March 15, 2023",
      genre: ["Horror", "Fantasy"],
      actor: ["Max Schreck", "Greta Schröder", "Gustav von Wangenheim"],
      director: ["F. W. Murnau"],
      trailerUrl: "https://www.youtube.com/watch?v=FC6jFoYm3xs",
      status: "Now Showing",
    },
    {
      id: "mufasa",
      title: "Mufasa",
      image:
        "https://assets.voxcinemas.com/posters/P_HO00011415_1734002132521.jpg",
      description: "The Lion King Returns",
      longDescription:
        "Mufasa explores the legendary journey of the Lion King himself, delving into his early struggles, relationships, and ultimate rise to greatness. This visually stunning prequel to 'The Lion King' promises to captivate audiences of all ages with its heartwarming story and breathtaking animation.",
      size: "small",
      highlight: "Excessive Preview",
      rating: 7.9,
      duration: "02 hours 10 minutes",
      language: "English",
      releaseDate: "July 7, 2024",
      genre: ["Animation", "Adventure", "Drama"],
      actor: ["James Earl Jones", "Jeremy Irons", "Matthew Broderick"],
      director: ["Jon Favreau"],
      trailerUrl: "https://www.youtube.com/watch?v=7TavVZMewpY",
      status: "Coming Soon",
    },
    {
      id: "sonic-3",
      title: "Sonic 3",
      image:
        "https://assets.voxcinemas.com/posters/P_HO00011450_1724997905981.jpg",
      description: "Speed has no limits",
      longDescription:
        "Sonic 3 brings our favorite blue hedgehog back for an action-packed adventure. With new allies and enemies, Sonic faces his greatest challenge yet as he races against time to save the world. Packed with humor, heart, and high-speed thrills, this movie is a must-watch for fans of all ages.",
      highlight: "Coming Soon",
      size: "small",
      rating: 7.2,
      duration: "01 hours 55 minutes",
      language: "English",
      releaseDate: "December 20, 2023",
      genre: ["Animation", "Action", "Comedy"],
      actor: ["Ben Schwartz", "Idris Elba", "Jim Carrey"],
      director: ["Jeff Fowler"],
      trailerUrl: "https://www.youtube.com/watch?v=n7UO2hHvJx4",
      status: "Coming Soon",
    },
    {
      id: "marco",
      title: "Marco",
      image:
        "https://assets.voxcinemas.com/posters/P_HO00011837_1735283944255.jpg",
      description: "A journey begins",
      longDescription:
        "Marco follows the story of a young boy embarking on an extraordinary journey across continents. Filled with adventure, self-discovery, and awe-inspiring landscapes, this film is a beautiful ode to the spirit of exploration and the bonds that define us.",
      size: "small",
      highlight: "Book Now",
      rating: 8.0,
      duration: "02 hours 00 minutes",
      language: "English",
      releaseDate: "June 1, 2023",
      genre: ["Drama", "Adventure"],
      actor: ["John Doe", "Jane Smith", "Emily Brown"],
      director: ["Alice Johnson"],
      trailerUrl: "https://www.youtube.com/watch?v=exampleMarco",
      status: "Now Showing",
    },
    {
      id: "identity",
      title: "Identity",
      image:
        "https://assets.voxcinemas.com/posters/P_HO00011817_1734505836119.jpg",
      description: "Who can you trust?",
      longDescription:
        "Identity is a psychological thriller that keeps you guessing until the very end. Ten strangers find themselves stranded at a remote motel during a storm, but as their numbers dwindle, they realize their connection to a dark and shocking secret.",
      highlight: "Final Week",
      size: "small",
      rating: 7.8,
      duration: "01 hours 50 minutes",
      language: "English",
      releaseDate: "May 10, 2023",
      genre: ["Thriller", "Mystery"],
      actor: ["John Cusack", "Ray Liotta", "Amanda Peet"],
      director: ["James Mangold"],
      trailerUrl: "https://www.youtube.com/watch?v=exampleIdentity",
      status: "Now Showing",
    },
    {
      id: "the-last-stand",
      title: "The Last Stand",
      image:
        "https://assets.voxcinemas.com/posters/P_HO00011201_1724765243551.jpg",
      description: "One final battle",
      longDescription:
        "The Last Stand is an adrenaline-pumping action movie that follows a retired sheriff who must defend his small town from a dangerous cartel leader. With explosive action sequences and gripping performances, it’s a thrilling ride from start to finish.",
      size: "large",
      highlight: "Book Now",
      rating: 8.1,
      duration: "02 hours 15 minutes",
      language: "English",
      releaseDate: "March 10, 2023",
      genre: ["Action", "Drama"],
      actor: ["Arnold Schwarzenegger", "Forest Whitaker"],
      director: ["Kim Jee-woon"],
      trailerUrl: "https://www.youtube.com/watch?v=exampleLastStand",
      status: "Now Showing",
    },
    {
      id: "the-last-stand-alt",
      title: "The Last Stand",
      image: "/api/placeholder/800/600",
      description: "One final battle",
      longDescription:
        "In this alternate take on The Last Stand, the stakes are raised as the sheriff faces additional challenges from unexpected allies and enemies. This version delves deeper into the characters' backstories and motivations, offering a fresh perspective on the action-packed narrative.",
      size: "large",
      highlight: "Coming Soon",
      rating: 8.1,
      duration: "02 hours 15 minutes",
      language: "English",
      releaseDate: "March 10, 2023",
      genre: ["Action", "Drama"],
      actor: ["Arnold Schwarzenegger", "Forest Whitaker"],
      director: ["Kim Jee-woon"],
      trailerUrl: "https://www.youtube.com/watch?v=exampleLastStandAlt",
      status: "Coming Soon",
    },
  ];
  
  
  