# Generated by Django 5.1.5 on 2025-01-27 03:12

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.SlugField(
                        editable=False,
                        max_length=255,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.CharField(max_length=255)),
                ("longDescription", models.TextField()),
                ("image", models.CharField(max_length=255)),
                ("rating", models.DecimalField(decimal_places=1, max_digits=3)),
                ("duration", models.CharField(max_length=255)),
                ("highlight", models.CharField(max_length=255)),
                ("size", models.CharField(max_length=100)),
                ("language", models.CharField(max_length=100)),
                ("actor", models.JSONField()),
                ("director", models.CharField(max_length=255)),
                ("trailerUrl", models.CharField(max_length=255)),
                ("status", models.CharField(max_length=255)),
            ],
        ),
    ]
