# Generated by Django 5.1.5 on 2025-01-29 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0002_movie_releasedate"),
        ("showing", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="showing",
            name="movie",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="showings",
                to="movies.movie",
            ),
        ),
        migrations.AlterField(
            model_name="showing",
            name="date",
            field=models.DateField(),
        ),
        migrations.DeleteModel(
            name="Movie",
        ),
    ]
